[package]
name = "sectxtlib"
version = "0.4.1"
authors = ["eikendev"]
edition = "2024"
rust-version = "1.85" # Required by edition 2024.
description = "A library for parsing and validating security.txt files as specified in RFC 9116"
homepage = "https://github.com/eikendev/sectxt"
repository = "https://github.com/eikendev/sectxt"
readme = "README.md"
license = "ISC"

[dependencies]
chrono = "0.4.20"
iri-string = "0.7.12"
nom = "8"
oxilangtag = "0.1.6"
thiserror = "2.0"
valuable = { version = "0.1.1", features = ["derive"] }
